"""
File Management for Oriz
Handles file operations, dist analysis, and asset management
"""

import os
import sys
import shutil
import hashlib
import json
from pathlib import Path
from datetime import datetime

sys.path.insert(0, str(Path(__file__).parent))
from config import PROJECT_ROOT, DIST_DIR


def analyze_dist():
    """Analyze the dist directory and report file sizes"""
    print("\n📊 Dist Directory Analysis")
    print("=" * 60)

    if not DIST_DIR.exists():
        print("❌ Dist directory not found. Run 'npm run build' first.")
        return None

    total_size = 0
    file_count = 0
    type_sizes: dict[str, int] = {}
    files_info = []

    for file_path in sorted(DIST_DIR.rglob('*')):
        if file_path.is_file():
            size = file_path.stat().st_size
            total_size += size
            file_count += 1

            ext = file_path.suffix.lower() or '(none)'
            type_sizes[ext] = type_sizes.get(ext, 0) + size

            relative = file_path.relative_to(DIST_DIR)
            files_info.append({
                'path': str(relative),
                'size': size,
                'ext': ext,
            })

    # Display results
    print(f"\n  📁 Total files: {file_count}")
    print(f"  📦 Total size: {format_size(total_size)}")

    print(f"\n  📋 By file type:")
    for ext, size in sorted(type_sizes.items(), key=lambda x: -x[1]):
        print(f"     {ext:10} {format_size(size):>10}")

    print(f"\n  📄 All files:")
    for info in sorted(files_info, key=lambda x: -x['size']):
        print(f"     {format_size(info['size']):>10}  {info['path']}")

    return {
        'total_size': total_size,
        'file_count': file_count,
        'type_sizes': type_sizes,
        'files': files_info,
    }


def verify_build_integrity():
    """Verify the build output contains expected files"""
    print("\n🔍 Build Integrity Check")
    print("=" * 60)

    required_files = [
        'index.html',
        'robots.txt',
        'favicon.svg',
        '_headers',
    ]

    expected_dirs = [
        'assets',
    ]

    all_ok = True

    for filename in required_files:
        filepath = DIST_DIR / filename
        if filepath.exists():
            print(f"  ✅ {filename} ({format_size(filepath.stat().st_size)})")
        else:
            print(f"  ❌ {filename} — MISSING")
            all_ok = False

    for dirname in expected_dirs:
        dirpath = DIST_DIR / dirname
        if dirpath.exists() and dirpath.is_dir():
            count = sum(1 for _ in dirpath.rglob('*') if _.is_file())
            print(f"  ✅ {dirname}/ ({count} files)")
        else:
            print(f"  ⚠️ {dirname}/ — not found (may be OK if no assets)")

    # Check index.html contains essential elements
    index_html = DIST_DIR / 'index.html'
    if index_html.exists():
        content = index_html.read_text(encoding='utf-8')
        checks = [
            ('<meta', 'Meta tags'),
            ('og:title', 'Open Graph'),
            ('fin.oriz.in', 'FinSuit link'),
            ('dev.oriz.in', 'DevSuit link'),
            ('<script', 'JavaScript bundle'),
        ]
        for marker, label in checks:
            if marker in content:
                print(f"  ✅ {label} found in index.html")
            else:
                print(f"  ⚠️ {label} NOT found in index.html")
                all_ok = False

    if all_ok:
        print("\n✅ Build integrity check passed!")
    else:
        print("\n⚠️ Some integrity checks failed")

    return all_ok


def generate_checksums():
    """Generate SHA256 checksums for all dist files"""
    print("\n🔐 Generating checksums...")

    if not DIST_DIR.exists():
        print("❌ Dist directory not found")
        return {}

    checksums = {}

    for file_path in sorted(DIST_DIR.rglob('*')):
        if file_path.is_file():
            sha256 = hashlib.sha256()
            with open(file_path, 'rb') as f:
                for chunk in iter(lambda: f.read(8192), b''):
                    sha256.update(chunk)

            relative = str(file_path.relative_to(DIST_DIR))
            checksums[relative] = sha256.hexdigest()

    # Save checksums file
    checksums_file = DIST_DIR / 'checksums.json'
    checksums_file.write_text(json.dumps(checksums, indent=2), encoding='utf-8')
    print(f"  ✅ Saved {len(checksums)} checksums to checksums.json")

    return checksums


def clean_build():
    """Remove dist, node_modules/.cache, and other build artifacts"""
    print("\n🧹 Cleaning build artifacts...")

    dirs_to_clean = [
        DIST_DIR,
        PROJECT_ROOT / '.vite',
        PROJECT_ROOT / 'node_modules' / '.cache',
    ]

    files_to_clean = [
        PROJECT_ROOT / 'vercel.json',  # Auto-generated by deploy_vercel
    ]

    for dirpath in dirs_to_clean:
        if dirpath.exists():
            try:
                shutil.rmtree(dirpath)
                print(f"  ✅ Removed {dirpath.relative_to(PROJECT_ROOT)}")
            except Exception as e:
                print(f"  ⚠️ Could not remove {dirpath}: {e}")

    for filepath in files_to_clean:
        if filepath.exists():
            try:
                filepath.unlink()
                print(f"  ✅ Removed {filepath.relative_to(PROJECT_ROOT)}")
            except Exception as e:
                print(f"  ⚠️ Could not remove {filepath}: {e}")

    print("  ✅ Clean complete")


def backup_dist():
    """Create a timestamped backup of the dist directory"""
    if not DIST_DIR.exists():
        print("❌ Nothing to backup — dist not found")
        return None

    timestamp = datetime.now().strftime('%Y%m%d_%H%M%S')
    backup_dir = PROJECT_ROOT / 'backups' / f'dist_{timestamp}'
    backup_dir.parent.mkdir(parents=True, exist_ok=True)

    try:
        shutil.copytree(DIST_DIR, backup_dir)
        print(f"✅ Backup created: {backup_dir.relative_to(PROJECT_ROOT)}")
        return str(backup_dir)
    except Exception as e:
        print(f"❌ Backup failed: {e}")
        return None


def list_project_structure():
    """List the project file structure with sizes"""
    print(f"\n📁 Project Structure: {PROJECT_ROOT.name}")
    print("=" * 60)

    ignore_dirs = {'.git', 'node_modules', 'dist', '.vite', 'backups', '__pycache__'}

    for root, dirs, files in os.walk(PROJECT_ROOT):
        # Filter ignored directories
        dirs[:] = [d for d in dirs if d not in ignore_dirs]

        level = len(Path(root).relative_to(PROJECT_ROOT).parts)
        indent = "  " * level
        folder_name = Path(root).name
        if level == 0:
            folder_name = PROJECT_ROOT.name
        print(f"{indent}📂 {folder_name}/")

        sub_indent = "  " * (level + 1)
        for file in sorted(files):
            filepath = Path(root) / file
            size = filepath.stat().st_size
            print(f"{sub_indent}📄 {file} ({format_size(size)})")


def format_size(size_bytes: int) -> str:
    """Format bytes to human-readable size"""
    if size_bytes < 1024:
        return f"{size_bytes} B"
    elif size_bytes < 1024 * 1024:
        return f"{size_bytes / 1024:.1f} KB"
    else:
        return f"{size_bytes / (1024 * 1024):.2f} MB"


if __name__ == '__main__':
    print("=" * 50)
    print("📂 Oriz File Management")
    print("=" * 50)

    args = sys.argv[1:]

    if '--analyze' in args:
        analyze_dist()
    elif '--verify' in args:
        verify_build_integrity()
    elif '--checksums' in args:
        generate_checksums()
    elif '--clean' in args:
        clean_build()
    elif '--backup' in args:
        backup_dist()
    elif '--structure' in args:
        list_project_structure()
    else:
        print("\nUsage:")
        print("  python manage_files.py --analyze      Analyze dist directory")
        print("  python manage_files.py --verify       Verify build integrity")
        print("  python manage_files.py --checksums    Generate file checksums")
        print("  python manage_files.py --clean        Clean build artifacts")
        print("  python manage_files.py --backup       Backup dist directory")
        print("  python manage_files.py --structure    List project structure")
